./problem_manager.sh h8_h5
./problem_manager.sh h8_h4
./problem_manager.sh h8_h3
./problem_manager.sh h8_h2
./problem_manager.sh h8_h1
./problem_manager.sh h8_g4
./problem_manager.sh h8_g5
./problem_manager.sh h8_g3
./problem_manager.sh h8_g2
./problem_manager.sh h8_g1
./problem_manager.sh h8_f5
./problem_manager.sh h8_f4
./problem_manager.sh h8_f3
./problem_manager.sh h8_f2
./problem_manager.sh h8_f1
./problem_manager.sh h8_e5
./problem_manager.sh h8_e4
./problem_manager.sh h8_e3
./problem_manager.sh h8_e2
./problem_manager.sh h8_e1
./problem_manager.sh h8_d4
./problem_manager.sh h8_d3
./problem_manager.sh h8_d2
./problem_manager.sh h8_d1
./problem_manager.sh h8_c3
./problem_manager.sh h8_c2
./problem_manager.sh h8_c1
./problem_manager.sh h8_b2
./problem_manager.sh h8_b1
./problem_manager.sh h8_a1
